const GET_FAVORITE_NEWS_REQUEST = 'GET_FAVORITE_NEWS_REQUEST';
const GET_FAVORITE_NEWS_REQUEST_SUCCESS = 'GET_FAVORITE_NEWS_REQUEST_SUCCESS';
const GET_FAVORITE_NEWS_REQUEST_FAILURE = 'GET_FAVORITE_NEWS_REQUEST_FAILURE';

const ADD_TO_FAVORITE_NEWS_REQUEST = 'ADD_TO_FAVORITE_NEWS_REQUEST';
const ADD_TO_FAVORITE_NEWS_REQUEST_SUCCESS =
  'ADD_TO_FAVORITE_NEWS_REQUEST_SUCCESS';
const ADD_TO_FAVORITE_NEWS_REQUEST_FAILURE =
  'ADD_TO_FAVORITE_NEWS_REQUEST_FAILURE';

const REMOVE_FROM_FAVORITE_NEWS_REQUEST = 'REMOVE_FROM_FAVORITE_NEWS_REQUEST';
const REMOVE_FROM_FAVORITE_NEWS_REQUEST_SUCCESS =
  'REMOVE_FROM_FAVORITE_NEWS_REQUEST_SUCCESS';
const REMOVE_FROM_FAVORITE_NEWS_REQUEST_FAILURE =
  'REMOVE_FROM_FAVORITE_NEWS_REQUEST_FAILURE';

export {
  GET_FAVORITE_NEWS_REQUEST,
  GET_FAVORITE_NEWS_REQUEST_SUCCESS,
  GET_FAVORITE_NEWS_REQUEST_FAILURE,
  ADD_TO_FAVORITE_NEWS_REQUEST,
  ADD_TO_FAVORITE_NEWS_REQUEST_SUCCESS,
  ADD_TO_FAVORITE_NEWS_REQUEST_FAILURE,
  REMOVE_FROM_FAVORITE_NEWS_REQUEST,
  REMOVE_FROM_FAVORITE_NEWS_REQUEST_SUCCESS,
  REMOVE_FROM_FAVORITE_NEWS_REQUEST_FAILURE,
};
