const SIGNIN_USER_REQUEST = 'SIGNIN_USER_REQUEST';

const SIGNIN_USER_REQUEST_SUCCESS = 'SIGNIN_USER_REQUEST_SUCCESS';
const SIGNIN_USER_REQUEST_FAILURE = 'SIGNIN_USER_REQUEST_FAILURE';

export {
  SIGNIN_USER_REQUEST,
  SIGNIN_USER_REQUEST_SUCCESS,
  SIGNIN_USER_REQUEST_FAILURE,
};
